name: descubre_narino
description: "App para descubrir eventos culturales en Nariño"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  image_picker: ^1.2.0
  firebase_storage: ^13.0.3
  cloudinary_public: ^0.23.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  http: ^1.5.0
  flutter_typeahead: ^5.2.0

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  
  # Estado y navegación
  provider: ^6.1.1
  
  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.4.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_oficial.png